src_data_dir: "/work/users/a/m/amjada/sim_rescaling/sim_results/test/1_1"
output_dir: "/work/users/a/m/amjada/sim_rescaling/sim_results/test/results"
chr_len: 1000
batch_size: 100
conda_env: "envs/simscale_sm.yml"